SELECT
  TABLE_NAME,
  ENGINE,
  TABLE_COLLATION
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND LOWER(TABLE_NAME) IN ('clientes', 'usuarios', 'pets', 'pet_fichas');

SELECT
  TABLE_NAME,
  COLUMN_NAME,
  COLUMN_TYPE,
  IS_NULLABLE,
  COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND (
    (LOWER(TABLE_NAME) = 'clientes' AND LOWER(COLUMN_NAME) = 'id')
    OR (LOWER(TABLE_NAME) = 'usuarios' AND LOWER(COLUMN_NAME) IN ('usuario_id', 'cliente_id', 'usuario_login'))
    OR (LOWER(TABLE_NAME) = 'pets' AND LOWER(COLUMN_NAME) IN ('id', 'cliente_id'))
    OR (LOWER(TABLE_NAME) = 'pet_fichas' AND LOWER(COLUMN_NAME) IN ('id', 'pet_id'))
  )
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT
  CONSTRAINT_NAME,
  TABLE_NAME,
  COLUMN_NAME,
  REFERENCED_TABLE_NAME,
  REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE()
  AND LOWER(TABLE_NAME) IN ('pets', 'pet_fichas')
  AND REFERENCED_TABLE_NAME IS NOT NULL;
