const db = require("../config/database");
const { sendPendingPaymentReminder } = require("./hostingNotificationService");
const PENDING = ["aguardando_comprovante","aguardando_pagamento","aguardando_link","reprovado"];
let timer=null,running=false;
const clean=v=>String(v||"").trim();
const normal=v=>clean(v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
function today(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).reduce((o,x)=>{if(["year","month","day"].includes(x.type))o[x.type]=x.value;return o;},{});return Date.UTC(+p.year,+p.month-1,+p.day)}
function until(v){const m=clean(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?Math.round((Date.UTC(+m[1],+m[2]-1,+m[3])-today())/86400000):null}
function cycleStart(created,comp){const d=clean(created).match(/^\d{4}-\d{2}-(\d{2})/),m=clean(comp).match(/^(\d{4})-(\d{2})/);if(!d||!m)return "";const day=Math.min(+d[1],new Date(Date.UTC(+m[1],+m[2],0)).getUTCDate());return m[1]+"-"+m[2]+"-"+String(day).padStart(2,"0")}
function isFifteenDayType(type){const v=normal(type);return v.includes("day")||v.includes("hospedagem")||v.includes("hotel")}
async function ensure(){await db.query("CREATE TABLE IF NOT EXISTS Hospedagem_Lembretes_Pagamento (id INT NOT NULL AUTO_INCREMENT,pagamento_id INT NOT NULL,tipo_lembrete VARCHAR(20) NOT NULL,enviado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uk_hosp_lembrete_pagamento(pagamento_id,tipo_lembrete)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")}
async function send(row,type){const [old]=await db.query("SELECT id FROM Hospedagem_Lembretes_Pagamento WHERE pagamento_id=? AND tipo_lembrete=? LIMIT 1",[row.paymentId,type]);if(old[0]||!clean(row.tutorEmail))return;const out=await sendPendingPaymentReminder({tutorEmail:row.tutorEmail,tutorName:row.tutorName,pets:row.pets});if(out&&out.sent)await db.query("INSERT IGNORE INTO Hospedagem_Lembretes_Pagamento(pagamento_id,tipo_lembrete) VALUES(?,?)",[row.paymentId,type])}
async function rows(monthly){const marks=PENDING.map(()=>"?").join(",");const join=monthly?"JOIN Hospedagem_Mensalidades m ON m.pagamento_id=p.id":"";const extra=monthly?",m.competencia,s.criado_em requestCreatedAt":",COALESCE(MAX(i.tipo),s.tipo) requestType,COALESCE(MIN(i.data_entrada),s.data_entrada) requestStart";const [r]=await db.query("SELECT p.id paymentId"+extra+",c.nome tutorName,c.email tutorEmail,GROUP_CONCAT(DISTINCT COALESCE(i.pet_nome,pet.nome) SEPARATOR ', ') pets FROM Hospedagem_Pagamentos p "+join+" JOIN Hospedagem_Solicitacoes s ON s.id=p.solicitacao_id JOIN Clientes c ON c.id=s.cliente_id LEFT JOIN Hospedagem_Solicitacao_Itens i ON i.solicitacao_id=s.id LEFT JOIN Pets pet ON pet.id=i.pet_id WHERE LOWER(p.status) IN ("+marks+") AND LOWER(s.status) IN ('aprovado','confirmado') "+(monthly?"":"AND LOWER(COALESCE(s.modo_cobranca,''))<>'mensal' ")+"GROUP BY p.id,s.id,c.id"+(monthly?",m.id":""),PENDING);return r||[]}
async function runPaymentReminderCheck(){if(running)return;running=true;try{await ensure();for(const r of await rows(false)){const d=until(r.requestStart);if(d===15&&isFifteenDayType(r.requestType))await send(r,"15_dias");if(d===1)await send(r,"1_dia")}for(const r of await rows(true))if(until(cycleStart(r.requestCreatedAt,r.competencia))===1)await send(r,"1_dia")}catch(e){console.error("Payment reminder check failed:",e.message||e)}finally{running=false}}
function startPaymentReminderService(){if(timer)return;runPaymentReminderCheck();timer=setInterval(runPaymentReminderCheck,3600000);timer.unref&&timer.unref()}
function stopPaymentReminderService(){if(timer)clearInterval(timer);timer=null}
module.exports={startPaymentReminderService,stopPaymentReminderService,runPaymentReminderCheck};
